export const COLORS = {
    "red": { bg: "bg-red-500", text: "text-red-500", border: "border-red-500" },
    "orange": { bg: "bg-orange-500", text: "text-orange-500", border: "border-orange-500" },
    "yellow": { bg: "bg-yellow-500", text: "text-yellow-500", border: "border-yellow-500" },
    "lime": { bg: "bg-lime-500", text: "text-lime-500", border: "border-lime-500" },
    "green": { bg: "bg-green-500", text: "text-green-500", border: "border-green-500" },
    "emerald": { bg: "bg-emerald-500", text: "text-emerald-500", border: "border-emerald-500" },
    "teal": { bg: "bg-teal-500", text: "text-teal-500", border: "border-teal-500" },
    "cyan": { bg: "bg-cyan-500", text: "text-cyan-500", border: "border-cyan-500" },
    "sky": { bg: "bg-sky-500", text: "text-sky-500", border: "border-sky-500" },
    "blue": { bg: "bg-blue-500", text: "text-blue-500", border: "border-blue-500" },
    "indigo": { bg: "bg-indigo-500", text: "text-indigo-500", border: "border-indigo-500" },
    "violet": { bg: "bg-violet-500", text: "text-violet-500", border: "border-violet-500" },
    "purple": { bg: "bg-purple-500", text: "text-purple-500", border: "border-purple-500" },
    "fuchsia": { bg: "bg-fuchsia-500", text: "text-fuchsia-500", border: "border-fuchsia-500" },
    "pink": { bg: "bg-pink-500", text: "text-pink-500", border: "border-pink-500" },
    "rose": { bg: "bg-rose-500", text: "text-rose-500", border: "border-rose-500" },
}